-type length () :: integer().
-type localmmktdate () :: string().
-type time () :: string().
-type date () :: string().
-type data () :: string().
-type monthYear () :: string().
-type dayOfMonth () :: integer().
-type account () :: string().
-type advId () :: string().
-type advRefID () :: string().
-type advSide () :: buy|sell|trade|cross.
-type advTransType () :: cancel|new|replace.
-type avgPx () :: float().
-type beginSeqNo () :: integer().
-type beginString () :: string().
-type bodyLength () :: integer().
-type checkSum () :: string().
-type clOrdID () :: string().
-type commission () :: float().
-type commType () :: perUnit|percent|absolute.
-type cumQty () :: integer().
-type currency () :: string().
-type endSeqNo () :: integer().
-type execID () :: string().
-type execInst () :: stayOnOfferSide|notHeld|work|goAlong|overTheDay|held|participateDoNotInitiate|strictScale|tryToScale|stayOnBidSide|noCross|oKToCross|callFirst|percentOfVolume|doNotIncrease|doNotReduce|allOrNone|institutionsOnly|lastPeg|midPricePeg|nonNegotiable|openingPeg|marketPeg|primaryPeg|suspend|customerDisplayInstruction|netting.
-type execRefID () :: string().
-type execTransType () :: new|cancel|correct|status.
-type handlInst () :: automatedExecutionNoIntervention|automatedExecutionInterventionOK|manualOrder.
-type iDSource () :: cUSIP|sEDOL|qUIK|iSINNumber|rICCode|iSOCurrencyCode|iSOCountryCode.
-type iOIid () :: string().
-type iOIOthSvc () :: autex|bridge.
-type iOIQltyInd () :: high|low|medium.
-type iOIRefID () :: string().
-type iOIShares () :: large|medium|small.
-type iOITransType () :: cancel|new|replace.
-type lastCapacity () :: agent|crossAsAgent|crossAsPrincipal|principal.
-type lastMkt () :: string().
-type lastPx () :: float().
-type lastShares () :: integer().
-type linesOfText () :: integer().
-type msgSeqNum () :: integer().
-type msgType () :: heartbeat|testRequest|resendRequest|reject|sequenceReset|logout|iOI|advertisement|executionReport|orderCancelReject|logon|news|email|orderSingle|newOrderList|orderCancelRequest|orderCancelReplaceRequest|orderStatusRequest|allocationInstruction|listCancelRequest|listExecute|listStatusRequest|listStatus|allocationInstructionAck|dontKnowTrade|quoteRequest|quote|settlementInstructions.
-type newSeqNo () :: integer().
-type orderID () :: string().
-type orderQty () :: integer().
-type ordStatus () :: new|partiallyFilled|filled|doneForDay|canceled|replaced|pendingCancel|stopped|rejected|suspended|pendingNew|calculated|expired.
-type ordType () :: market|limit|stop|stopLimit|marketOnClose|withOrWithout|limitOrBetter|limitWithOrWithout|onBasis|onClose|limitOnClose|forexMarket|previouslyQuoted|previouslyIndicated|forexLimit|forexSwap|forexPreviouslyQuoted|pegged.
-type origClOrdID () :: string().
-type origTime () :: time().
-type possDupFlag () :: originalTransmission|possibleDuplicate.
-type price () :: float().
-type refSeqNum () :: integer().
-type relatdSym () :: string().
-type rule80A () :: agencySingleOrder|shortExemptTransactionAType|proprietaryNonAlgo|programOrderMember|shortExemptTransactionForPrincipal|shortExemptTransactionWType|shortExemptTransactionIType|individualInvestor|proprietaryAlgo|agencyAlgo|shortExemptTransactionMemberAffliated|programOrderOtherMember|agentForOtherMember|proprietaryTransactionAffiliated|principal|transactionNonMember|specialistTrades|transactionUnaffiliatedMember|agencyIndexArb|allOtherOrdersAsAgentForOtherMember|shortExemptTransactionMemberNotAffliated|agencyNonAlgo|shortExemptTransactionNonMember.
-type securityID () :: string().
-type senderCompID () :: string().
-type senderSubID () :: string().
-type sendingTime () :: time().
-type shares () :: integer().
-type side () :: buy|sell|buyMinus|sellPlus|sellShort|sellShortExempt|undisclosed|cross.
-type symbol () :: string().
-type targetCompID () :: string().
-type targetSubID () :: string().
-type text () :: string().
-type timeInForce () :: day|goodTillCancel|atTheOpening|immediateOrCancel|fillOrKill|goodTillCrossing|goodTillDate.
-type transactTime () :: time().
-type urgency () :: normal|flash|background.
-type validUntilTime () :: time().
-type settlmntTyp () :: regular|cash|nextDay|tPlus2|tPlus3|tPlus4|future|whenAndIfIssued|sellersOption|tPlus5.
-type futSettDate () :: date().
-type symbolSfx () :: string().
-type listID () :: string().
-type listSeqNo () :: integer().
-type listNoOrds () :: integer().
-type listExecInst () :: string().
-type allocID () :: string().
-type allocTransType () :: new|replace|cancel|preliminary|calculated.
-type refAllocID () :: string().
-type noOrders () :: integer().
-type avgPrxPrecision () :: integer().
-type tradeDate () :: date().
-type execBroker () :: string().
-type openClose () :: close|open.
-type noAllocs () :: integer().
-type allocAccount () :: string().
-type allocShares () :: integer().
-type processCode () :: regular|softDollar|stepIn|stepOut|softDollarStepIn|softDollarStepOut|planSponsor.
-type noRpts () :: integer().
-type rptSeq () :: integer().
-type cxlQty () :: integer().
-type allocStatus () :: accepted|blockLevelReject|accountLevelReject|received.
-type allocRejCode () :: unknownAccount|incorrectQuantity|incorrectAveragegPrice|unknownExecutingBrokerMnemonic|commissionDifference|unknownOrderID|unknownListID|otherSeeText.
-type signature () :: data().
-type secureDataLen () :: length().
-type secureData () :: data().
-type brokerOfCredit () :: string().
-type signatureLength () :: length().
-type emailType () :: new|reply|adminReply.
-type rawDataLength () :: length().
-type rawData () :: data().
-type possResend () :: originalTransmission|possibleResend.
-type encryptMethod () :: none|pKCS|dES|pKCSDES|pGPDES|pGPDESMD5|pEM.
-type stopPx () :: float().
-type exDestination () :: string().
-type cxlRejReason () :: tooLateToCancel|unknownOrder.
-type ordRejReason () :: brokerCredit|unknownSymbol|exchangeClosed|orderExceedsLimit|tooLateToEnter|unknownOrder|duplicateOrder.
-type iOIQualifier () :: allOrNone|atTheClose|inTouchWith|limit|moreBehind|atTheOpen|takingAPosition|atTheMarket|portfolioShown|throughTheDay|versus|indication|crossingOpportunity|atTheMidpoint|preOpen.
-type waveNo () :: string().
-type issuer () :: string().
-type securityDesc () :: string().
-type heartBtInt () :: integer().
-type clientID () :: string().
-type minQty () :: integer().
-type maxFloor () :: integer().
-type testReqID () :: string().
-type reportToExch () :: senderReports|receiverReports.
-type locateReqd () :: no|yes.
-type onBehalfOfCompID () :: string().
-type onBehalfOfSubID () :: string().
-type quoteID () :: string().
-type netMoney () :: float().
-type settlCurrAmt () :: float().
-type settlCurrency () :: string().
-type forexReq () :: doNotExecuteForexAfterSecurityTrade|executeForexAfterSecurityTrade.
-type origSendingTime () :: time().
-type gapFillFlag () :: sequenceReset|gapFillMessage.
-type noExecs () :: integer().
-type expireTime () :: time().
-type dKReason () :: unknownSymbol|wrongSide|quantityExceedsOrder|noMatchingOrder|priceExceedsLimit|other.
-type deliverToCompID () :: string().
-type deliverToSubID () :: string().
-type iOINaturalFlag () :: notNatural|natural.
-type quoteReqID () :: string().
-type bidPx () :: float().
-type offerPx () :: float().
-type bidSize () :: integer().
-type offerSize () :: integer().
-type noMiscFees () :: integer().
-type miscFeeAmt () :: float().
-type miscFeeCurr () :: string().
-type miscFeeType () :: regulatory|tax|localCommission|exchangeFees|stamp|levy|other|markup.
-type prevClosePx () :: float().
-type resetSeqNumFlag () :: no|yes.
-type senderLocationID () :: string().
-type targetLocationID () :: string().
-type onBehalfOfLocationID () :: string().
-type deliverToLocationID () :: string().
-type noRelatedSym () :: integer().
-type subject () :: string().
-type headline () :: string().
-type uRLLink () :: string().
-type execType () :: new|partialFill|fill|doneForDay|canceled|replaced|pendingCancel|stopped|rejected|suspended|pendingNew|calculated|expired.
-type leavesQty () :: integer().
-type cashOrderQty () :: float().
-type allocAvgPx () :: float().
-type allocNetMoney () :: float().
-type settlCurrFxRate () :: float().
-type settlCurrFxRateCalc () :: string().
-type numDaysInterest () :: integer().
-type accruedInterestRate () :: float().
-type accruedInterestAmt () :: float().
-type settlInstMode () :: default|standingInstructionsProvided|specificAllocationAccountOverriding|specificAllocationAccountStanding.
-type allocText () :: string().
-type settlInstID () :: string().
-type settlInstTransType () :: cancel|new|replace.
-type emailThreadID () :: string().
-type settlInstSource () :: brokerCredit|institution.
-type settlLocation () :: cEDEL|depositoryTrustCompany|euroClear|federalBookEntry|localMarketSettleLocation|physical|participantTrustCompany.
-type securityType () :: bankersAcceptance|certificateOfDeposit|collateralizedMortgageObligation|corporateBond|commercialPaper|corporatePrivatePlacement|commonStock|federalHousingAuthority|federalHomeLoan|federalNationalMortgageAssociation|foreignExchangeContract|future|governmentNationalMortgageAssociation|treasuriesAgencyDebenture|mutualFund|mortgageInterestOnly|mortgagePrincipalOnly|mortgagePrivatePlacement|miscellaneousPassThrough|municipalBond|noSecurityType|option|preferredStock|repurchaseAgreement|reverseRepurchaseAgreement|studentLoanMarketingAssociation|timeDeposit|uSTreasuryBillOld|warrant|catsTigersAndLions.
-type effectiveTime () :: time().
-type standInstDbType () :: other|dTCSID|thomsonALERT|aGlobalCustodian.
-type standInstDbName () :: string().
-type standInstDbID () :: string().
-type settlDeliveryType () :: integer().
-type settlDepositoryCode () :: string().
-type settlBrkrCode () :: string().
-type settlInstCode () :: string().
-type securitySettlAgentName () :: string().
-type securitySettlAgentCode () :: string().
-type securitySettlAgentAcctNum () :: string().
-type securitySettlAgentAcctName () :: string().
-type securitySettlAgentContactName () :: string().
-type securitySettlAgentContactPhone () :: string().
-type cashSettlAgentName () :: string().
-type cashSettlAgentCode () :: string().
-type cashSettlAgentAcctNum () :: string().
-type cashSettlAgentAcctName () :: string().
-type cashSettlAgentContactName () :: string().
-type cashSettlAgentContactPhone () :: string().
-type bidSpotRate () :: float().
-type bidForwardPoints () :: float().
-type offerSpotRate () :: float().
-type offerForwardPoints () :: float().
-type orderQty2 () :: float().
-type futSettDate2 () :: date().
-type lastSpotRate () :: float().
-type lastForwardPoints () :: float().
-type allocLinkID () :: string().
-type allocLinkType () :: fXNetting|fXSwap.
-type secondaryOrderID () :: string().
-type noIOIQualifiers () :: integer().
-type maturityMonthYear () :: monthYear().
-type putOrCall () :: put|call.
-type strikePrice () :: float().
-type coveredOrUncovered () :: covered|uncovered.
-type customerOrFirm () :: customer|firm.
-type maturityDay () :: dayOfMonth().
-type optAttribute () :: string().
-type securityExchange () :: string().
-type notifyBrokerOfCredit () :: detailsShouldNotBeCommunicated|detailsShouldBeCommunicated.
-type allocHandlInst () :: match|forward|forwardAndMatch.
-type maxShow () :: integer().
-type pegDifference () :: float().
-record( standardHeader, {beginString :: beginString(), bodyLength :: bodyLength(), msgType :: msgType(), senderCompID :: senderCompID(), targetCompID :: targetCompID(), onBehalfOfCompID :: onBehalfOfCompID(), deliverToCompID :: deliverToCompID(), secureDataLen :: secureDataLen(), secureData :: secureData(), msgSeqNum :: msgSeqNum(), senderSubID :: senderSubID(), senderLocationID :: senderLocationID(), targetSubID :: targetSubID(), targetLocationID :: targetLocationID(), onBehalfOfSubID :: onBehalfOfSubID(), onBehalfOfLocationID :: onBehalfOfLocationID(), deliverToSubID :: deliverToSubID(), deliverToLocationID :: deliverToLocationID(), possDupFlag :: possDupFlag(), possResend :: possResend(), sendingTime :: sendingTime(), origSendingTime :: origSendingTime()}).
-record( standardTrailer, {signatureLength :: signatureLength(), signature :: signature(), checkSum :: checkSum()}).
-record( heartbeat, {standardHeader :: #standardHeader{}, testReqID :: testReqID(), standardTrailer :: #standardTrailer{}}).
-record( testRequest, {standardHeader :: #standardHeader{}, testReqID :: testReqID(), standardTrailer :: #standardTrailer{}}).
-record( resendRequest, {standardHeader :: #standardHeader{}, beginSeqNo :: beginSeqNo(), endSeqNo :: endSeqNo(), standardTrailer :: #standardTrailer{}}).
-record( reject, {standardHeader :: #standardHeader{}, refSeqNum :: refSeqNum(), text :: text(), standardTrailer :: #standardTrailer{}}).
-record( sequenceReset, {standardHeader :: #standardHeader{}, gapFillFlag :: gapFillFlag(), newSeqNo :: newSeqNo(), standardTrailer :: #standardTrailer{}}).
-record( logout, {standardHeader :: #standardHeader{}, text :: text(), standardTrailer :: #standardTrailer{}}).
-record( rgr_iOI_199, {iOIQualifier :: iOIQualifier()}).
-record( iOI, {standardHeader :: #standardHeader{}, iOIid :: iOIid(), iOITransType :: iOITransType(), iOIRefID :: iOIRefID(), symbol :: symbol(), symbolSfx :: symbolSfx(), securityID :: securityID(), iDSource :: iDSource(), securityType :: securityType(), maturityMonthYear :: maturityMonthYear(), maturityDay :: maturityDay(), putOrCall :: putOrCall(), strikePrice :: strikePrice(), optAttribute :: optAttribute(), securityExchange :: securityExchange(), issuer :: issuer(), securityDesc :: securityDesc(), side :: side(), iOIShares :: iOIShares(), price :: price(), currency :: currency(), validUntilTime :: validUntilTime(), iOIQltyInd :: iOIQltyInd(), iOIOthSvc :: iOIOthSvc(), iOINaturalFlag :: iOINaturalFlag(), rgr_iOI_199 = [#rgr_iOI_199{}], text :: text(), transactTime :: transactTime(), uRLLink :: uRLLink(), standardTrailer :: #standardTrailer{}}).
-record( advertisement, {standardHeader :: #standardHeader{}, advId :: advId(), advTransType :: advTransType(), advRefID :: advRefID(), symbol :: symbol(), symbolSfx :: symbolSfx(), securityID :: securityID(), iDSource :: iDSource(), securityType :: securityType(), maturityMonthYear :: maturityMonthYear(), maturityDay :: maturityDay(), putOrCall :: putOrCall(), strikePrice :: strikePrice(), optAttribute :: optAttribute(), securityExchange :: securityExchange(), issuer :: issuer(), securityDesc :: securityDesc(), advSide :: advSide(), shares :: shares(), price :: price(), currency :: currency(), tradeDate :: tradeDate(), transactTime :: transactTime(), text :: text(), uRLLink :: uRLLink(), lastMkt :: lastMkt(), standardTrailer :: #standardTrailer{}}).
-record( executionReport, {standardHeader :: #standardHeader{}, orderID :: orderID(), secondaryOrderID :: secondaryOrderID(), clOrdID :: clOrdID(), origClOrdID :: origClOrdID(), clientID :: clientID(), execBroker :: execBroker(), listID :: listID(), execID :: execID(), execTransType :: execTransType(), execRefID :: execRefID(), execType :: execType(), ordStatus :: ordStatus(), ordRejReason :: ordRejReason(), account :: account(), settlmntTyp :: settlmntTyp(), futSettDate :: futSettDate(), symbol :: symbol(), symbolSfx :: symbolSfx(), securityID :: securityID(), iDSource :: iDSource(), securityType :: securityType(), maturityMonthYear :: maturityMonthYear(), maturityDay :: maturityDay(), putOrCall :: putOrCall(), strikePrice :: strikePrice(), optAttribute :: optAttribute(), securityExchange :: securityExchange(), issuer :: issuer(), securityDesc :: securityDesc(), side :: side(), orderQty :: orderQty(), ordType :: ordType(), price :: price(), stopPx :: stopPx(), pegDifference :: pegDifference(), currency :: currency(), timeInForce :: timeInForce(), expireTime :: expireTime(), execInst :: execInst(), rule80A :: rule80A(), lastShares :: lastShares(), lastPx :: lastPx(), lastSpotRate :: lastSpotRate(), lastForwardPoints :: lastForwardPoints(), lastMkt :: lastMkt(), lastCapacity :: lastCapacity(), leavesQty :: leavesQty(), cumQty :: cumQty(), avgPx :: avgPx(), tradeDate :: tradeDate(), transactTime :: transactTime(), reportToExch :: reportToExch(), commission :: commission(), commType :: commType(), settlCurrAmt :: settlCurrAmt(), settlCurrency :: settlCurrency(), settlCurrFxRate :: settlCurrFxRate(), settlCurrFxRateCalc :: settlCurrFxRateCalc(), text :: text(), standardTrailer :: #standardTrailer{}}).
-record( orderCancelReject, {standardHeader :: #standardHeader{}, orderID :: orderID(), secondaryOrderID :: secondaryOrderID(), clOrdID :: clOrdID(), origClOrdID :: origClOrdID(), ordStatus :: ordStatus(), clientID :: clientID(), execBroker :: execBroker(), listID :: listID(), cxlRejReason :: cxlRejReason(), text :: text(), standardTrailer :: #standardTrailer{}}).
-record( logon, {standardHeader :: #standardHeader{}, encryptMethod :: encryptMethod(), heartBtInt :: heartBtInt(), rawDataLength :: rawDataLength(), rawData :: rawData(), resetSeqNumFlag :: resetSeqNumFlag(), standardTrailer :: #standardTrailer{}}).
-record( rgr_news_146, {relatdSym :: relatdSym(), symbolSfx :: symbolSfx(), securityID :: securityID(), iDSource :: iDSource(), securityType :: securityType(), maturityMonthYear :: maturityMonthYear(), maturityDay :: maturityDay(), putOrCall :: putOrCall(), strikePrice :: strikePrice(), optAttribute :: optAttribute(), securityExchange :: securityExchange(), issuer :: issuer(), securityDesc :: securityDesc()}).
-record( rgr_news_33, {text :: text()}).
-record( news, {standardHeader :: #standardHeader{}, origTime :: origTime(), urgency :: urgency(), headline :: headline(), rgr_news_146 = [#rgr_news_146{}], rgr_news_33 = [#rgr_news_33{}], uRLLink :: uRLLink(), rawDataLength :: rawDataLength(), rawData :: rawData(), standardTrailer :: #standardTrailer{}}).
-record( rgr_email_146, {relatdSym :: relatdSym(), symbolSfx :: symbolSfx(), securityID :: securityID(), iDSource :: iDSource(), securityType :: securityType(), maturityMonthYear :: maturityMonthYear(), maturityDay :: maturityDay(), putOrCall :: putOrCall(), strikePrice :: strikePrice(), optAttribute :: optAttribute(), securityExchange :: securityExchange(), issuer :: issuer(), securityDesc :: securityDesc()}).
-record( rgr_email_33, {text :: text()}).
-record( email, {standardHeader :: #standardHeader{}, emailThreadID :: emailThreadID(), emailType :: emailType(), origTime :: origTime(), subject :: subject(), rgr_email_146 = [#rgr_email_146{}], orderID :: orderID(), clOrdID :: clOrdID(), rgr_email_33 = [#rgr_email_33{}], rawDataLength :: rawDataLength(), rawData :: rawData(), standardTrailer :: #standardTrailer{}}).
-record( orderSingle, {standardHeader :: #standardHeader{}, clOrdID :: clOrdID(), clientID :: clientID(), execBroker :: execBroker(), account :: account(), settlmntTyp :: settlmntTyp(), futSettDate :: futSettDate(), handlInst :: handlInst(), execInst :: execInst(), minQty :: minQty(), maxFloor :: maxFloor(), exDestination :: exDestination(), processCode :: processCode(), symbol :: symbol(), symbolSfx :: symbolSfx(), securityID :: securityID(), iDSource :: iDSource(), securityType :: securityType(), maturityMonthYear :: maturityMonthYear(), maturityDay :: maturityDay(), putOrCall :: putOrCall(), strikePrice :: strikePrice(), optAttribute :: optAttribute(), securityExchange :: securityExchange(), issuer :: issuer(), securityDesc :: securityDesc(), prevClosePx :: prevClosePx(), side :: side(), locateReqd :: locateReqd(), orderQty :: orderQty(), cashOrderQty :: cashOrderQty(), ordType :: ordType(), price :: price(), stopPx :: stopPx(), currency :: currency(), iOIid :: iOIid(), quoteID :: quoteID(), timeInForce :: timeInForce(), expireTime :: expireTime(), commission :: commission(), commType :: commType(), rule80A :: rule80A(), forexReq :: forexReq(), settlCurrency :: settlCurrency(), text :: text(), futSettDate2 :: futSettDate2(), orderQty2 :: orderQty2(), openClose :: openClose(), coveredOrUncovered :: coveredOrUncovered(), customerOrFirm :: customerOrFirm(), maxShow :: maxShow(), pegDifference :: pegDifference(), standardTrailer :: #standardTrailer{}}).
-record( newOrderList, {standardHeader :: #standardHeader{}, listID :: listID(), waveNo :: waveNo(), listSeqNo :: listSeqNo(), listNoOrds :: listNoOrds(), listExecInst :: listExecInst(), clOrdID :: clOrdID(), clientID :: clientID(), execBroker :: execBroker(), account :: account(), settlmntTyp :: settlmntTyp(), futSettDate :: futSettDate(), handlInst :: handlInst(), execInst :: execInst(), minQty :: minQty(), maxFloor :: maxFloor(), exDestination :: exDestination(), processCode :: processCode(), symbol :: symbol(), symbolSfx :: symbolSfx(), securityID :: securityID(), iDSource :: iDSource(), securityType :: securityType(), maturityMonthYear :: maturityMonthYear(), maturityDay :: maturityDay(), putOrCall :: putOrCall(), strikePrice :: strikePrice(), optAttribute :: optAttribute(), securityExchange :: securityExchange(), issuer :: issuer(), securityDesc :: securityDesc(), prevClosePx :: prevClosePx(), side :: side(), locateReqd :: locateReqd(), orderQty :: orderQty(), ordType :: ordType(), price :: price(), stopPx :: stopPx(), pegDifference :: pegDifference(), currency :: currency(), timeInForce :: timeInForce(), expireTime :: expireTime(), commission :: commission(), commType :: commType(), rule80A :: rule80A(), forexReq :: forexReq(), settlCurrency :: settlCurrency(), text :: text(), futSettDate2 :: futSettDate2(), orderQty2 :: orderQty2(), openClose :: openClose(), coveredOrUncovered :: coveredOrUncovered(), customerOrFirm :: customerOrFirm(), maxShow :: maxShow(), standardTrailer :: #standardTrailer{}}).
-record( orderCancelRequest, {standardHeader :: #standardHeader{}, origClOrdID :: origClOrdID(), orderID :: orderID(), clOrdID :: clOrdID(), listID :: listID(), clientID :: clientID(), execBroker :: execBroker(), symbol :: symbol(), symbolSfx :: symbolSfx(), securityID :: securityID(), iDSource :: iDSource(), securityType :: securityType(), maturityMonthYear :: maturityMonthYear(), maturityDay :: maturityDay(), putOrCall :: putOrCall(), strikePrice :: strikePrice(), optAttribute :: optAttribute(), securityExchange :: securityExchange(), issuer :: issuer(), securityDesc :: securityDesc(), side :: side(), orderQty :: orderQty(), cashOrderQty :: cashOrderQty(), text :: text(), standardTrailer :: #standardTrailer{}}).
-record( orderCancelReplaceRequest, {standardHeader :: #standardHeader{}, orderID :: orderID(), clientID :: clientID(), execBroker :: execBroker(), origClOrdID :: origClOrdID(), clOrdID :: clOrdID(), listID :: listID(), account :: account(), settlmntTyp :: settlmntTyp(), futSettDate :: futSettDate(), handlInst :: handlInst(), execInst :: execInst(), minQty :: minQty(), maxFloor :: maxFloor(), exDestination :: exDestination(), symbol :: symbol(), symbolSfx :: symbolSfx(), securityID :: securityID(), iDSource :: iDSource(), securityType :: securityType(), maturityMonthYear :: maturityMonthYear(), maturityDay :: maturityDay(), putOrCall :: putOrCall(), strikePrice :: strikePrice(), optAttribute :: optAttribute(), securityExchange :: securityExchange(), issuer :: issuer(), securityDesc :: securityDesc(), side :: side(), orderQty :: orderQty(), cashOrderQty :: cashOrderQty(), ordType :: ordType(), price :: price(), stopPx :: stopPx(), pegDifference :: pegDifference(), currency :: currency(), timeInForce :: timeInForce(), expireTime :: expireTime(), commission :: commission(), commType :: commType(), rule80A :: rule80A(), forexReq :: forexReq(), settlCurrency :: settlCurrency(), text :: text(), futSettDate2 :: futSettDate2(), orderQty2 :: orderQty2(), openClose :: openClose(), coveredOrUncovered :: coveredOrUncovered(), customerOrFirm :: customerOrFirm(), maxShow :: maxShow(), locateReqd :: locateReqd(), standardTrailer :: #standardTrailer{}}).
-record( orderStatusRequest, {standardHeader :: #standardHeader{}, orderID :: orderID(), clOrdID :: clOrdID(), clientID :: clientID(), execBroker :: execBroker(), symbol :: symbol(), symbolSfx :: symbolSfx(), securityID :: securityID(), iDSource :: iDSource(), securityType :: securityType(), maturityMonthYear :: maturityMonthYear(), maturityDay :: maturityDay(), putOrCall :: putOrCall(), strikePrice :: strikePrice(), optAttribute :: optAttribute(), securityExchange :: securityExchange(), issuer :: issuer(), securityDesc :: securityDesc(), side :: side(), standardTrailer :: #standardTrailer{}}).
-record( rgr_allocationInstruction_73, {clOrdID :: clOrdID(), orderID :: orderID(), secondaryOrderID :: secondaryOrderID(), listID :: listID(), waveNo :: waveNo()}).
-record( rgr_allocationInstruction_124, {lastShares :: lastShares(), execID :: execID(), lastPx :: lastPx(), lastCapacity :: lastCapacity()}).
-record( rgr_rgr_allocationInstruction_78_136, {miscFeeAmt :: miscFeeAmt(), miscFeeCurr :: miscFeeCurr(), miscFeeType :: miscFeeType()}).
-record( rgr_allocationInstruction_78, {allocAccount :: allocAccount(), allocShares :: allocShares(), processCode :: processCode(), brokerOfCredit :: brokerOfCredit(), notifyBrokerOfCredit :: notifyBrokerOfCredit(), allocHandlInst :: allocHandlInst(), allocText :: allocText(), execBroker :: execBroker(), clientID :: clientID(), commission :: commission(), commType :: commType(), allocAvgPx :: allocAvgPx(), allocNetMoney :: allocNetMoney(), settlCurrAmt :: settlCurrAmt(), settlCurrency :: settlCurrency(), settlCurrFxRate :: settlCurrFxRate(), settlCurrFxRateCalc :: settlCurrFxRateCalc(), accruedInterestAmt :: accruedInterestAmt(), settlInstMode :: settlInstMode(), rgr_rgr_allocationInstruction_78_136 :: [#rgr_rgr_allocationInstruction_78_136{}]}).
-record( allocationInstruction, {standardHeader :: #standardHeader{}, allocID :: allocID(), allocTransType :: allocTransType(), refAllocID :: refAllocID(), allocLinkID :: allocLinkID(), allocLinkType :: allocLinkType(), rgr_allocationInstruction_73 = [#rgr_allocationInstruction_73{}], rgr_allocationInstruction_124 = [#rgr_allocationInstruction_124{}], side :: side(), symbol :: symbol(), symbolSfx :: symbolSfx(), securityID :: securityID(), iDSource :: iDSource(), securityType :: securityType(), maturityMonthYear :: maturityMonthYear(), maturityDay :: maturityDay(), putOrCall :: putOrCall(), strikePrice :: strikePrice(), optAttribute :: optAttribute(), securityExchange :: securityExchange(), issuer :: issuer(), securityDesc :: securityDesc(), shares :: shares(), lastMkt :: lastMkt(), avgPx :: avgPx(), currency :: currency(), avgPrxPrecision :: avgPrxPrecision(), tradeDate :: tradeDate(), transactTime :: transactTime(), settlmntTyp :: settlmntTyp(), futSettDate :: futSettDate(), netMoney :: netMoney(), openClose :: openClose(), text :: text(), numDaysInterest :: numDaysInterest(), accruedInterestRate :: accruedInterestRate(), rgr_allocationInstruction_78 = [#rgr_allocationInstruction_78{}], standardTrailer :: #standardTrailer{}}).
-record( listCancelRequest, {standardHeader :: #standardHeader{}, listID :: listID(), waveNo :: waveNo(), text :: text(), standardTrailer :: #standardTrailer{}}).
-record( listExecute, {standardHeader :: #standardHeader{}, listID :: listID(), waveNo :: waveNo(), text :: text(), standardTrailer :: #standardTrailer{}}).
-record( listStatusRequest, {standardHeader :: #standardHeader{}, listID :: listID(), waveNo :: waveNo(), text :: text(), standardTrailer :: #standardTrailer{}}).
-record( rgr_listStatus_73, {clOrdID :: clOrdID(), cumQty :: cumQty(), leavesQty :: leavesQty(), cxlQty :: cxlQty(), avgPx :: avgPx()}).
-record( listStatus, {standardHeader :: #standardHeader{}, listID :: listID(), waveNo :: waveNo(), noRpts :: noRpts(), rptSeq :: rptSeq(), rgr_listStatus_73 = [#rgr_listStatus_73{}], standardTrailer :: #standardTrailer{}}).
-record( allocationInstructionAck, {standardHeader :: #standardHeader{}, clientID :: clientID(), execBroker :: execBroker(), allocID :: allocID(), tradeDate :: tradeDate(), transactTime :: transactTime(), allocStatus :: allocStatus(), allocRejCode :: allocRejCode(), text :: text(), standardTrailer :: #standardTrailer{}}).
-record( dontKnowTrade, {standardHeader :: #standardHeader{}, orderID :: orderID(), execID :: execID(), dKReason :: dKReason(), symbol :: symbol(), symbolSfx :: symbolSfx(), securityID :: securityID(), iDSource :: iDSource(), securityType :: securityType(), maturityMonthYear :: maturityMonthYear(), maturityDay :: maturityDay(), putOrCall :: putOrCall(), strikePrice :: strikePrice(), optAttribute :: optAttribute(), securityExchange :: securityExchange(), issuer :: issuer(), securityDesc :: securityDesc(), side :: side(), orderQty :: orderQty(), cashOrderQty :: cashOrderQty(), lastShares :: lastShares(), lastPx :: lastPx(), text :: text(), standardTrailer :: #standardTrailer{}}).
-record( quoteRequest, {standardHeader :: #standardHeader{}, quoteReqID :: quoteReqID(), symbol :: symbol(), symbolSfx :: symbolSfx(), securityID :: securityID(), iDSource :: iDSource(), securityType :: securityType(), maturityMonthYear :: maturityMonthYear(), maturityDay :: maturityDay(), putOrCall :: putOrCall(), strikePrice :: strikePrice(), optAttribute :: optAttribute(), securityExchange :: securityExchange(), issuer :: issuer(), securityDesc :: securityDesc(), prevClosePx :: prevClosePx(), side :: side(), orderQty :: orderQty(), futSettDate :: futSettDate(), ordType :: ordType(), futSettDate2 :: futSettDate2(), orderQty2 :: orderQty2(), standardTrailer :: #standardTrailer{}}).
-record( quote, {standardHeader :: #standardHeader{}, quoteReqID :: quoteReqID(), quoteID :: quoteID(), symbol :: symbol(), symbolSfx :: symbolSfx(), securityID :: securityID(), iDSource :: iDSource(), securityType :: securityType(), maturityMonthYear :: maturityMonthYear(), maturityDay :: maturityDay(), putOrCall :: putOrCall(), strikePrice :: strikePrice(), optAttribute :: optAttribute(), securityExchange :: securityExchange(), issuer :: issuer(), securityDesc :: securityDesc(), bidPx :: bidPx(), offerPx :: offerPx(), bidSize :: bidSize(), offerSize :: offerSize(), validUntilTime :: validUntilTime(), bidSpotRate :: bidSpotRate(), offerSpotRate :: offerSpotRate(), bidForwardPoints :: bidForwardPoints(), offerForwardPoints :: offerForwardPoints(), transactTime :: transactTime(), futSettDate :: futSettDate(), ordType :: ordType(), futSettDate2 :: futSettDate2(), orderQty2 :: orderQty2(), standardTrailer :: #standardTrailer{}}).
-record( settlementInstructions, {standardHeader :: #standardHeader{}, settlInstID :: settlInstID(), settlInstTransType :: settlInstTransType(), settlInstMode :: settlInstMode(), settlInstSource :: settlInstSource(), allocAccount :: allocAccount(), settlLocation :: settlLocation(), tradeDate :: tradeDate(), allocID :: allocID(), lastMkt :: lastMkt(), side :: side(), securityType :: securityType(), effectiveTime :: effectiveTime(), transactTime :: transactTime(), clientID :: clientID(), execBroker :: execBroker(), standInstDbType :: standInstDbType(), standInstDbName :: standInstDbName(), standInstDbID :: standInstDbID(), settlDeliveryType :: settlDeliveryType(), settlDepositoryCode :: settlDepositoryCode(), settlBrkrCode :: settlBrkrCode(), settlInstCode :: settlInstCode(), securitySettlAgentName :: securitySettlAgentName(), securitySettlAgentCode :: securitySettlAgentCode(), securitySettlAgentAcctNum :: securitySettlAgentAcctNum(), securitySettlAgentAcctName :: securitySettlAgentAcctName(), securitySettlAgentContactName :: securitySettlAgentContactName(), securitySettlAgentContactPhone :: securitySettlAgentContactPhone(), cashSettlAgentName :: cashSettlAgentName(), cashSettlAgentCode :: cashSettlAgentCode(), cashSettlAgentAcctNum :: cashSettlAgentAcctNum(), cashSettlAgentAcctName :: cashSettlAgentAcctName(), cashSettlAgentContactName :: cashSettlAgentContactName(), cashSettlAgentContactPhone :: cashSettlAgentContactPhone(), standardTrailer :: #standardTrailer{}}).
