-type length () :: integer().
-type time () :: string().
-type date () :: string().
-type data () :: string().
-type account () :: string().
-type advId () :: integer().
-type advRefID () :: integer().
-type advSide () :: buy|sell|trade|cross.
-type advTransType () :: cancel|new|replace.
-type avgPx () :: float().
-type beginSeqNo () :: integer().
-type beginString () :: string().
-type bodyLength () :: integer().
-type checkSum () :: string().
-type clOrdID () :: string().
-type commission () :: float().
-type commType () :: perUnit|percent|absolute.
-type cumQty () :: integer().
-type currency () :: string().
-type endSeqNo () :: integer().
-type execID () :: integer().
-type execInst () :: stayOnOfferSide|notHeld|work|goAlong|overTheDay|held|participateDoNotInitiate|strictScale|tryToScale|stayOnBidSide|noCross|oKToCross|callFirst|percentOfVolume|doNotIncrease|doNotReduce|allOrNone|institutionsOnly|lastPeg|midPricePeg|nonNegotiable|openingPeg|marketPeg|primaryPeg|suspend.
-type execRefID () :: integer().
-type execTransType () :: new|cancel|correct|status.
-type handlInst () :: automatedExecutionNoIntervention|automatedExecutionInterventionOK|manualOrder.
-type iDSource () :: cUSIP|sEDOL|qUIK|iSINNumber|rICCode.
-type iOIid () :: integer().
-type iOIOthSvc () :: autex|bridge.
-type iOIQltyInd () :: high|low|medium.
-type iOIRefID () :: integer().
-type iOIShares () :: large|medium|small.
-type iOITransType () :: cancel|new|replace.
-type lastCapacity () :: agent|crossAsAgent|crossAsPrincipal|principal.
-type lastMkt () :: string().
-type lastPx () :: float().
-type lastShares () :: integer().
-type linesOfText () :: integer().
-type msgSeqNum () :: integer().
-type msgType () :: heartbeat|testRequest|resendRequest|reject|sequenceReset|logout|iOI|advertisement|executionReport|orderCancelReject|logon|news|email|orderSingle|newOrderList|orderCancelRequest|orderCancelReplaceRequest|orderStatusRequest|allocationInstruction|listCancelRequest|listExecute|listStatusRequest|listStatus|allocationInstructionAck|dontKnowTrade|quoteRequest|quote.
-type newSeqNo () :: integer().
-type orderID () :: string().
-type orderQty () :: integer().
-type ordStatus () :: new|partiallyFilled|filled|doneForDay|canceled|replaced|pendingCancel|stopped|rejected|suspended|pendingNew|calculated|expired.
-type ordType () :: market|limit|stop|stopLimit|marketOnClose|withOrWithout|limitOrBetter|limitWithOrWithout|onBasis|onClose|limitOnClose|forexMarket|previouslyQuoted|previouslyIndicated|pegged.
-type origClOrdID () :: string().
-type origTime () :: time().
-type possDupFlag () :: originalTransmission|possibleDuplicate.
-type price () :: float().
-type refSeqNum () :: integer().
-type relatdSym () :: string().
-type rule80A () :: agencySingleOrder|proprietaryNonAlgo|programOrderMember|individualInvestor|proprietaryAlgo|agencyAlgo|programOrderOtherMember|agentForOtherMember|agencyIndexArb|allOtherOrdersAsAgentForOtherMember|agencyNonAlgo.
-type securityID () :: string().
-type senderCompID () :: string().
-type senderSubID () :: string().
-type sendingTime () :: time().
-type shares () :: integer().
-type side () :: buy|sell|buyMinus|sellPlus|sellShort|sellShortExempt.
-type symbol () :: string().
-type targetCompID () :: string().
-type targetSubID () :: string().
-type text () :: string().
-type timeInForce () :: day|goodTillCancel|atTheOpening|immediateOrCancel|fillOrKill|goodTillCrossing|goodTillDate.
-type transactTime () :: time().
-type urgency () :: normal|flash|background.
-type validUntilTime () :: time().
-type settlmntTyp () :: regular|cash|nextDay|tPlus2|tPlus3|tPlus4|future|whenAndIfIssued|sellersOption|tPlus5.
-type futSettDate () :: date().
-type symbolSfx () :: string().
-type listID () :: string().
-type listSeqNo () :: integer().
-type listNoOrds () :: integer().
-type listExecInst () :: string().
-type allocID () :: integer().
-type allocTransType () :: new|replace|cancel.
-type refAllocID () :: integer().
-type noOrders () :: integer().
-type avgPrxPrecision () :: integer().
-type tradeDate () :: date().
-type execBroker () :: string().
-type openClose () :: string().
-type noAllocs () :: integer().
-type allocAccount () :: string().
-type allocShares () :: integer().
-type processCode () :: regular|softDollar|stepIn|stepOut|softDollarStepIn|softDollarStepOut|planSponsor.
-type noRpts () :: integer().
-type rptSeq () :: integer().
-type cxlQty () :: integer().
-type noDlvyInst () :: integer().
-type dlvyInst () :: string().
-type allocStatus () :: accepted|blockLevelReject|accountLevelReject|received.
-type allocRejCode () :: unknownAccount|incorrectQuantity|incorrectAveragegPrice|unknownExecutingBrokerMnemonic|commissionDifference|unknownOrderID|unknownListID|otherSeeText.
-type signature () :: data().
-type secureDataLen () :: length().
-type secureData () :: data().
-type brokerOfCredit () :: string().
-type signatureLength () :: length().
-type emailType () :: new|reply|adminReply.
-type rawDataLength () :: length().
-type rawData () :: data().
-type possResend () :: string().
-type encryptMethod () :: none|pKCS|dES|pKCSDES|pGPDES|pGPDESMD5|pEM.
-type stopPx () :: float().
-type exDestination () :: none|pOSIT.
-type cxlRejReason () :: tooLateToCancel|unknownOrder.
-type ordRejReason () :: brokerCredit|unknownSymbol|exchangeClosed|orderExceedsLimit|tooLateToEnter.
-type iOIQualifier () :: allOrNone|atTheClose|inTouchWith|limit|moreBehind|atTheOpen|takingAPosition|atTheMarket|portfolioShown|throughTheDay|versus|indication|crossingOpportunity.
-type waveNo () :: string().
-type issuer () :: string().
-type securityDesc () :: string().
-type heartBtInt () :: integer().
-type clientID () :: string().
-type minQty () :: integer().
-type maxFloor () :: integer().
-type testReqID () :: string().
-type reportToExch () :: senderReports|receiverReports.
-type locateReqd () :: no|yes.
-type onBehalfOfCompID () :: string().
-type onBehalfOfSubID () :: string().
-type quoteID () :: string().
-type netMoney () :: float().
-type settlCurrAmt () :: float().
-type settlCurrency () :: string().
-type forexReq () :: doNotExecuteForexAfterSecurityTrade|executeForexAfterSecurityTrade.
-type origSendingTime () :: time().
-type gapFillFlag () :: sequenceReset|gapFillMessage.
-type noExecs () :: integer().
-type cxlType () :: fullRemainingQuantity|partialCancel.
-type expireTime () :: time().
-type dKReason () :: unknownSymbol|wrongSide|quantityExceedsOrder|noMatchingOrder|priceExceedsLimit|other.
-type deliverToCompID () :: string().
-type deliverToSubID () :: string().
-type iOINaturalFlag () :: notNatural|natural.
-type quoteReqID () :: string().
-type bidPx () :: float().
-type offerPx () :: float().
-type bidSize () :: integer().
-type offerSize () :: integer().
-type noMiscFees () :: integer().
-type miscFeeAmt () :: float().
-type miscFeeCurr () :: string().
-type miscFeeType () :: regulatory|tax|localCommission|exchangeFees|stamp|levy|other.
-type prevClosePx () :: float().
-record( standardHeader, {beginString :: beginString(), bodyLength :: bodyLength(), msgType :: msgType(), senderCompID :: senderCompID(), targetCompID :: targetCompID(), onBehalfOfCompID :: onBehalfOfCompID(), deliverToCompID :: deliverToCompID(), secureDataLen :: secureDataLen(), secureData :: secureData(), msgSeqNum :: msgSeqNum(), senderSubID :: senderSubID(), targetSubID :: targetSubID(), onBehalfOfSubID :: onBehalfOfSubID(), deliverToSubID :: deliverToSubID(), possDupFlag :: possDupFlag(), possResend :: possResend(), sendingTime :: sendingTime(), origSendingTime :: origSendingTime()}).
-record( standardTrailer, {signatureLength :: signatureLength(), signature :: signature(), checkSum :: checkSum()}).
-record( heartbeat, {standardHeader :: #standardHeader{}, testReqID :: testReqID(), standardTrailer :: #standardTrailer{}}).
-record( testRequest, {standardHeader :: #standardHeader{}, testReqID :: testReqID(), standardTrailer :: #standardTrailer{}}).
-record( resendRequest, {standardHeader :: #standardHeader{}, beginSeqNo :: beginSeqNo(), endSeqNo :: endSeqNo(), standardTrailer :: #standardTrailer{}}).
-record( reject, {standardHeader :: #standardHeader{}, refSeqNum :: refSeqNum(), text :: text(), standardTrailer :: #standardTrailer{}}).
-record( sequenceReset, {standardHeader :: #standardHeader{}, gapFillFlag :: gapFillFlag(), newSeqNo :: newSeqNo(), standardTrailer :: #standardTrailer{}}).
-record( logout, {standardHeader :: #standardHeader{}, text :: text(), standardTrailer :: #standardTrailer{}}).
-record( iOI, {standardHeader :: #standardHeader{}, iOIid :: iOIid(), iOITransType :: iOITransType(), iOIRefID :: iOIRefID(), symbol :: symbol(), symbolSfx :: symbolSfx(), securityID :: securityID(), iDSource :: iDSource(), issuer :: issuer(), securityDesc :: securityDesc(), side :: side(), iOIShares :: iOIShares(), price :: price(), currency :: currency(), validUntilTime :: validUntilTime(), iOIQltyInd :: iOIQltyInd(), iOIOthSvc :: iOIOthSvc(), iOINaturalFlag :: iOINaturalFlag(), iOIQualifier :: iOIQualifier(), text :: text(), standardTrailer :: #standardTrailer{}}).
-record( advertisement, {standardHeader :: #standardHeader{}, advId :: advId(), advTransType :: advTransType(), advRefID :: advRefID(), symbol :: symbol(), symbolSfx :: symbolSfx(), securityID :: securityID(), iDSource :: iDSource(), issuer :: issuer(), securityDesc :: securityDesc(), advSide :: advSide(), shares :: shares(), price :: price(), currency :: currency(), transactTime :: transactTime(), text :: text(), standardTrailer :: #standardTrailer{}}).
-record( rgr_executionReport_136, {miscFeeAmt :: miscFeeAmt(), miscFeeCurr :: miscFeeCurr(), miscFeeType :: miscFeeType()}).
-record( executionReport, {standardHeader :: #standardHeader{}, orderID :: orderID(), clOrdID :: clOrdID(), clientID :: clientID(), execBroker :: execBroker(), listID :: listID(), execID :: execID(), execTransType :: execTransType(), execRefID :: execRefID(), ordStatus :: ordStatus(), ordRejReason :: ordRejReason(), account :: account(), settlmntTyp :: settlmntTyp(), futSettDate :: futSettDate(), symbol :: symbol(), symbolSfx :: symbolSfx(), securityID :: securityID(), iDSource :: iDSource(), issuer :: issuer(), securityDesc :: securityDesc(), side :: side(), orderQty :: orderQty(), ordType :: ordType(), price :: price(), stopPx :: stopPx(), currency :: currency(), timeInForce :: timeInForce(), expireTime :: expireTime(), execInst :: execInst(), rule80A :: rule80A(), lastShares :: lastShares(), lastPx :: lastPx(), lastMkt :: lastMkt(), lastCapacity :: lastCapacity(), cumQty :: cumQty(), avgPx :: avgPx(), tradeDate :: tradeDate(), transactTime :: transactTime(), reportToExch :: reportToExch(), commission :: commission(), commType :: commType(), rgr_executionReport_136 = [#rgr_executionReport_136{}], netMoney :: netMoney(), settlCurrAmt :: settlCurrAmt(), settlCurrency :: settlCurrency(), text :: text(), standardTrailer :: #standardTrailer{}}).
-record( orderCancelReject, {standardHeader :: #standardHeader{}, orderID :: orderID(), clOrdID :: clOrdID(), clientID :: clientID(), execBroker :: execBroker(), listID :: listID(), cxlRejReason :: cxlRejReason(), text :: text(), standardTrailer :: #standardTrailer{}}).
-record( logon, {standardHeader :: #standardHeader{}, encryptMethod :: encryptMethod(), heartBtInt :: heartBtInt(), rawDataLength :: rawDataLength(), rawData :: rawData(), standardTrailer :: #standardTrailer{}}).
-record( news, {standardHeader :: #standardHeader{}, origTime :: origTime(), urgency :: urgency(), relatdSym :: relatdSym(), linesOfText :: linesOfText(), text :: text(), rawDataLength :: rawDataLength(), rawData :: rawData(), standardTrailer :: #standardTrailer{}}).
-record( email, {standardHeader :: #standardHeader{}, emailType :: emailType(), origTime :: origTime(), relatdSym :: relatdSym(), orderID :: orderID(), clOrdID :: clOrdID(), linesOfText :: linesOfText(), text :: text(), rawDataLength :: rawDataLength(), rawData :: rawData(), standardTrailer :: #standardTrailer{}}).
-record( orderSingle, {standardHeader :: #standardHeader{}, clOrdID :: clOrdID(), clientID :: clientID(), execBroker :: execBroker(), account :: account(), settlmntTyp :: settlmntTyp(), futSettDate :: futSettDate(), handlInst :: handlInst(), execInst :: execInst(), minQty :: minQty(), maxFloor :: maxFloor(), exDestination :: exDestination(), processCode :: processCode(), symbol :: symbol(), symbolSfx :: symbolSfx(), securityID :: securityID(), iDSource :: iDSource(), issuer :: issuer(), securityDesc :: securityDesc(), prevClosePx :: prevClosePx(), side :: side(), locateReqd :: locateReqd(), orderQty :: orderQty(), ordType :: ordType(), price :: price(), stopPx :: stopPx(), currency :: currency(), iOIid :: iOIid(), quoteID :: quoteID(), timeInForce :: timeInForce(), expireTime :: expireTime(), commission :: commission(), commType :: commType(), rule80A :: rule80A(), forexReq :: forexReq(), settlCurrency :: settlCurrency(), text :: text(), standardTrailer :: #standardTrailer{}}).
-record( newOrderList, {standardHeader :: #standardHeader{}, listID :: listID(), waveNo :: waveNo(), listSeqNo :: listSeqNo(), listNoOrds :: listNoOrds(), listExecInst :: listExecInst(), clOrdID :: clOrdID(), clientID :: clientID(), execBroker :: execBroker(), account :: account(), settlmntTyp :: settlmntTyp(), futSettDate :: futSettDate(), handlInst :: handlInst(), execInst :: execInst(), minQty :: minQty(), maxFloor :: maxFloor(), exDestination :: exDestination(), processCode :: processCode(), symbol :: symbol(), symbolSfx :: symbolSfx(), securityID :: securityID(), iDSource :: iDSource(), issuer :: issuer(), securityDesc :: securityDesc(), prevClosePx :: prevClosePx(), side :: side(), locateReqd :: locateReqd(), orderQty :: orderQty(), ordType :: ordType(), price :: price(), stopPx :: stopPx(), currency :: currency(), timeInForce :: timeInForce(), expireTime :: expireTime(), commission :: commission(), commType :: commType(), rule80A :: rule80A(), forexReq :: forexReq(), settlCurrency :: settlCurrency(), text :: text(), standardTrailer :: #standardTrailer{}}).
-record( orderCancelRequest, {standardHeader :: #standardHeader{}, origClOrdID :: origClOrdID(), orderID :: orderID(), clOrdID :: clOrdID(), listID :: listID(), cxlType :: cxlType(), clientID :: clientID(), execBroker :: execBroker(), symbol :: symbol(), symbolSfx :: symbolSfx(), securityID :: securityID(), iDSource :: iDSource(), issuer :: issuer(), securityDesc :: securityDesc(), side :: side(), orderQty :: orderQty(), text :: text(), standardTrailer :: #standardTrailer{}}).
-record( orderCancelReplaceRequest, {standardHeader :: #standardHeader{}, orderID :: orderID(), clientID :: clientID(), execBroker :: execBroker(), origClOrdID :: origClOrdID(), clOrdID :: clOrdID(), listID :: listID(), account :: account(), settlmntTyp :: settlmntTyp(), futSettDate :: futSettDate(), handlInst :: handlInst(), execInst :: execInst(), minQty :: minQty(), maxFloor :: maxFloor(), exDestination :: exDestination(), symbol :: symbol(), symbolSfx :: symbolSfx(), securityID :: securityID(), iDSource :: iDSource(), issuer :: issuer(), securityDesc :: securityDesc(), side :: side(), orderQty :: orderQty(), ordType :: ordType(), price :: price(), stopPx :: stopPx(), currency :: currency(), timeInForce :: timeInForce(), expireTime :: expireTime(), commission :: commission(), commType :: commType(), rule80A :: rule80A(), forexReq :: forexReq(), settlCurrency :: settlCurrency(), text :: text(), standardTrailer :: #standardTrailer{}}).
-record( orderStatusRequest, {standardHeader :: #standardHeader{}, orderID :: orderID(), clOrdID :: clOrdID(), clientID :: clientID(), execBroker :: execBroker(), symbol :: symbol(), symbolSfx :: symbolSfx(), issuer :: issuer(), securityDesc :: securityDesc(), side :: side(), standardTrailer :: #standardTrailer{}}).
-record( rgr_allocationInstruction_73, {clOrdID :: clOrdID(), orderID :: orderID(), listID :: listID(), waveNo :: waveNo()}).
-record( rgr_allocationInstruction_124, {execID :: execID(), lastShares :: lastShares(), lastPx :: lastPx(), lastMkt :: lastMkt()}).
-record( rgr_allocationInstruction_136, {miscFeeAmt :: miscFeeAmt(), miscFeeCurr :: miscFeeCurr(), miscFeeType :: miscFeeType()}).
-record( rgr_allocationInstruction_78, {allocAccount :: allocAccount(), allocShares :: allocShares(), processCode :: processCode(), execBroker :: execBroker(), clientID :: clientID(), commission :: commission(), commType :: commType(), noDlvyInst :: noDlvyInst(), brokerOfCredit :: brokerOfCredit(), dlvyInst :: dlvyInst()}).
-record( allocationInstruction, {standardHeader :: #standardHeader{}, allocID :: allocID(), allocTransType :: allocTransType(), refAllocID :: refAllocID(), rgr_allocationInstruction_73 = [#rgr_allocationInstruction_73{}], rgr_allocationInstruction_124 = [#rgr_allocationInstruction_124{}], side :: side(), symbol :: symbol(), symbolSfx :: symbolSfx(), securityID :: securityID(), iDSource :: iDSource(), issuer :: issuer(), securityDesc :: securityDesc(), shares :: shares(), avgPx :: avgPx(), currency :: currency(), avgPrxPrecision :: avgPrxPrecision(), tradeDate :: tradeDate(), transactTime :: transactTime(), settlmntTyp :: settlmntTyp(), futSettDate :: futSettDate(), netMoney :: netMoney(), rgr_allocationInstruction_136 = [#rgr_allocationInstruction_136{}], settlCurrAmt :: settlCurrAmt(), settlCurrency :: settlCurrency(), openClose :: openClose(), text :: text(), rgr_allocationInstruction_78 = [#rgr_allocationInstruction_78{}], standardTrailer :: #standardTrailer{}}).
-record( listCancelRequest, {standardHeader :: #standardHeader{}, listID :: listID(), waveNo :: waveNo(), text :: text(), standardTrailer :: #standardTrailer{}}).
-record( listExecute, {standardHeader :: #standardHeader{}, listID :: listID(), waveNo :: waveNo(), text :: text(), standardTrailer :: #standardTrailer{}}).
-record( listStatusRequest, {standardHeader :: #standardHeader{}, listID :: listID(), waveNo :: waveNo(), text :: text(), standardTrailer :: #standardTrailer{}}).
-record( rgr_listStatus_73, {clOrdID :: clOrdID(), cumQty :: cumQty(), cxlQty :: cxlQty(), avgPx :: avgPx()}).
-record( listStatus, {standardHeader :: #standardHeader{}, listID :: listID(), waveNo :: waveNo(), noRpts :: noRpts(), rptSeq :: rptSeq(), rgr_listStatus_73 = [#rgr_listStatus_73{}], standardTrailer :: #standardTrailer{}}).
-record( allocationInstructionAck, {standardHeader :: #standardHeader{}, clientID :: clientID(), execBroker :: execBroker(), allocID :: allocID(), tradeDate :: tradeDate(), transactTime :: transactTime(), allocStatus :: allocStatus(), allocRejCode :: allocRejCode(), text :: text(), standardTrailer :: #standardTrailer{}}).
-record( dontKnowTrade, {standardHeader :: #standardHeader{}, orderID :: orderID(), execID :: execID(), dKReason :: dKReason(), symbol :: symbol(), side :: side(), orderQty :: orderQty(), lastShares :: lastShares(), lastPx :: lastPx(), text :: text(), standardTrailer :: #standardTrailer{}}).
-record( quoteRequest, {standardHeader :: #standardHeader{}, quoteReqID :: quoteReqID(), symbol :: symbol(), symbolSfx :: symbolSfx(), securityID :: securityID(), iDSource :: iDSource(), issuer :: issuer(), securityDesc :: securityDesc(), prevClosePx :: prevClosePx(), side :: side(), orderQty :: orderQty(), standardTrailer :: #standardTrailer{}}).
-record( quote, {standardHeader :: #standardHeader{}, quoteReqID :: quoteReqID(), quoteID :: quoteID(), symbol :: symbol(), symbolSfx :: symbolSfx(), securityID :: securityID(), iDSource :: iDSource(), issuer :: issuer(), securityDesc :: securityDesc(), bidPx :: bidPx(), offerPx :: offerPx(), bidSize :: bidSize(), offerSize :: offerSize(), validUntilTime :: validUntilTime(), standardTrailer :: #standardTrailer{}}).
